services:
  spacetickets-api:
    container_name: spacetickets-api
    image: petherin/spacetickets:latest
    environment:
      - API_PORT=8080
      - SWAGGER_PORT=8081
    ports:
      - 8080:8080
    networks:
      - spacetickets-network
    security_opt:
      - seccomp:unconfined

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: spacetickets-swagger
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/api/swagger.yaml
    volumes:
      - ./swagger.yaml:/api/swagger.yaml
    networks:
     - spacetickets-network
     
networks:
  spacetickets-network:
    name: spacetickets-network